#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

CONFIG_DIRS=(
  hypr waybar kitty mako nvim fastfetch cava rofi wofi
  gtk-3.0 gtk-4.0 qt5ct qt6ct waypaper xdg-desktop-portal
)

RSYNC_EXCLUDES=(
  --exclude '.cache'
  --exclude '*.log'
  --exclude '*.bak'
  --exclude '*.save'
  --exclude 'backups/'
  --exclude 'hyprland.local.conf'
  --exclude 'gtk.css'
  --exclude 'gtk-dark.css'
)

chmod_scripts() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] chmod +x %s/**/*.{sh,py}\n' "$dir"
    return 0
  fi
  find "$dir" -type f \( -name '*.sh' -o -name '*.py' \) -exec chmod +x {} +
}

rewrite_user_paths() {
  local qt6="$HOME/.config/qt6ct/qt6ct.conf"
  if [[ -f "$qt6" ]]; then
    log "ajustando rutas de qt6ct"
    if [[ "$DRY_RUN" -eq 1 ]]; then
      printf '[dry-run] sed HOME en %s\n' "$qt6"
    else
      sed -i "s|/REPLACE_HOME|$HOME|g; s|/home/candia|$HOME|g" "$qt6"
    fi
  fi
  local waypaper="$HOME/.config/waypaper/config.ini"
  if [[ -f "$waypaper" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      printf '[dry-run] sed HOME en %s\n' "$waypaper"
    else
      sed -i "s|/home/candia|$HOME|g" "$waypaper"
    fi
  fi
}

copy_config_dirs() {
  local name src dest
  ensure_dir "$HOME/.config"
  for name in "${CONFIG_DIRS[@]}"; do
    src="$REPO_ROOT/.config/$name"
    dest="$HOME/.config/$name"
    [[ -d "$src" ]] || continue
    backup_path "$dest"
    log "copiando $name"
    ensure_dir "$dest"
    run rsync -a "${RSYNC_EXCLUDES[@]}" "$src/" "$dest/"
  done
}

copy_wallpapers_dir() {
  ensure_dir "$HOME/Wallpaper-Bank/wallpapers"
  if compgen -G "$HOME/Wallpaper-Bank/wallpapers/*" >/dev/null; then
    ok "ya hay wallpapers en ~/Wallpaper-Bank/wallpapers"
    return 0
  fi
  warn "no hay imágenes en ~/Wallpaper-Bank/wallpapers"
  warn "coloca fondos ahí y ábrelos con waypaper (backend swww)"
}

generate_hypr_local() {
  local dest="$HOME/.config/hypr/hyprland.local.conf"
  local example="$REPO_ROOT/.config/hypr/hyprland.local.conf.example"
  ensure_dir "$HOME/.config/hypr"

  if [[ -f "$dest" ]]; then
    ok "se conserva $dest"
    return 0
  fi

  if command -v hyprctl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1 \
     && hyprctl monitors -j >/dev/null 2>&1; then
    log "detectando monitores con hyprctl"
    if [[ "$DRY_RUN" -eq 1 ]]; then
      printf '[dry-run] escribir %s desde hyprctl monitors\n' "$dest"
      return 0
    fi
    {
      echo "# Generated by DotfileCandia install.sh on $(date -Iseconds)"
      echo
      hyprctl monitors -j | jq -r '.[] | "monitor = \(.name), \(.width)x\(.height)@\(.refreshRate), auto, 1"'
      echo
      echo "monitor=,preferred,auto,1"
    } > "$dest"
    ok "escrito $dest"
    return 0
  fi

  log "usando template portable de monitores"
  if [[ -f "$example" ]]; then
    run cp "$example" "$dest"
  else
    if [[ "$DRY_RUN" -eq 1 ]]; then
      printf '[dry-run] escribir monitor=,preferred,auto,1 en %s\n' "$dest"
    else
      printf 'monitor=,preferred,auto,1\n' > "$dest"
    fi
  fi
}

usage() {
  cat <<'EOF'
Uso: link-configs.sh [--dry-run]
Copia las configs del rice a ~/.config (con backup).
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

parse_common_args "$@" || { usage; exit 1; }

command -v rsync >/dev/null 2>&1 || die "hace falta rsync"

copy_config_dirs
generate_hypr_local
rewrite_user_paths
copy_wallpapers_dir
chmod_scripts "$HOME/.config/waybar/scripts"
chmod_scripts "$HOME/.config/hypr"
chmod_scripts "$HOME/.config/hypr/scripts"
chmod_scripts "$HOME/.config/fastfetch/scripts"
ok "configs copiadas"
