#!/usr/bin/env python3
"""Generate circular progress ring PNGs and rings.css for Waybar."""

from __future__ import annotations

import math
from pathlib import Path

import cairo

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "rings"
CSS_PATH = ROOT / "rings.css"

SIZE = 40
CX = CY = SIZE / 2
STROKE = 7.2
RADIUS = (SIZE / 2) - (STROKE / 2) - 1.2

COLORS = {
    "blue": "#7aa2f7",
    "orange": "#e0af68",
    "green": "#9ece6a",
    "red": "#f7768e",
    "muted": "#565f89",
}

TRACK = (0x56 / 255, 0x5F / 255, 0x89 / 255, 0.42)
PERCENTS = list(range(0, 101, 5))


def hex_rgb(color: str) -> tuple[float, float, float]:
    value = color.lstrip("#")
    r, g, b = bytes.fromhex(value)
    return r / 255, g / 255, b / 255


def ring_png(percent: int, color: str, path: Path) -> None:
    surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, SIZE, SIZE)
    ctx = cairo.Context(surface)
    ctx.set_line_width(STROKE)

    ctx.set_source_rgba(*TRACK)
    ctx.arc(CX, CY, RADIUS, 0, 2 * math.pi)
    ctx.stroke()

    pct = max(0, min(100, percent))
    if pct > 0:
        start = -math.pi / 2
        extent = 2 * math.pi * (pct / 100)
        ctx.set_source_rgb(*hex_rgb(color))
        ctx.set_line_cap(cairo.LINE_CAP_ROUND)
        ctx.arc(CX, CY, RADIUS, start, start + extent)
        ctx.stroke()

    surface.write_to_png(str(path))


def css_url(path: Path) -> str:
    return f'url("file://{path}")'


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    for stale in ASSETS.glob("*"):
        stale.unlink()

    for name, color in COLORS.items():
        for pct in PERCENTS:
            ring_png(pct, color, ASSETS / f"{name}-{pct}.png")

    lines = [
        "/* Generated by scripts/gen-ring-assets.py — do not edit by hand */",
        "",
        "#custom-volume,",
        "#custom-brightness,",
        "#custom-battery {",
        "	min-width: 22px;",
        "	min-height: 22px;",
        "	padding: 0;",
        "	margin: 0 1px;",
        "	font-size: 1px;",
        "	color: transparent;",
        "	font-weight: 500;",
        "	background-color: transparent;",
        "	background-repeat: no-repeat;",
        "	background-position: center;",
        "	background-size: 22px 22px;",
        "}",
        "",
        "#custom-volume { color: transparent; }",
        "#custom-brightness { color: transparent; }",
        "#custom-battery { color: transparent; }",
        "#custom-volume.muted { color: transparent; }",
        "#custom-battery.warning { color: transparent; }",
        "#custom-battery.critical { color: transparent; }",
        "#custom-battery.charging,",
        "#custom-battery.plugged { color: transparent; }",
        "",
        "#custom-volume:hover,",
        "#custom-brightness:hover,",
        "#custom-battery:hover {",
        "	opacity: 0.8;",
        "}",
        "",
        "#custom-battery.critical:not(.charging):not(.plugged) {",
        "	animation: blink 0.5s linear infinite alternate;",
        "}",
        "",
    ]

    def rules(module: str, color: str, extra: str = "") -> None:
        for pct in PERCENTS:
            path = ASSETS / f"{color}-{pct}.png"
            lines.append(
                f"{module}{extra}.p{pct} {{ background-image: {css_url(path)}; }}"
            )
        lines.append("")

    rules("#custom-volume", "blue")
    rules("#custom-volume", "muted", extra=".muted")
    rules("#custom-brightness", "orange")
    rules("#custom-battery", "green")
    rules("#custom-battery", "orange", extra=".warning")
    rules("#custom-battery", "red", extra=".critical")

    CSS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(list(ASSETS.glob('*.png')))} PNGs to {ASSETS}")
    print(f"Wrote {CSS_PATH}")


if __name__ == "__main__":
    main()
